Controllers/PrefeituraController.cs
using Microsoft.AspNetCore.Mvc;
using Prefeituras.Data;
using Prefeituras.Models;
using Prefeituras.Repository;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Prefeituras.Controllers
{
    public class PrefeituraController : Controller
    {
        private readonly IPrefeituraRepository _prefeituraRepository;       

        public PrefeituraController(IPrefeituraRepository prefeituraRepository)
        {
            _prefeituraRepository = prefeituraRepository;         
        }
        public IActionResult Index()
        {
            var list = _prefeituraRepository.BuscarTodos();
            return View(list);
        }
        public IActionResult Cadastrar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {   
            var list = _prefeituraRepository.BuscarPorId(id);
            return View(list);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            var list = _prefeituraRepository.BuscarPorId(id);
            return View(list);
        }
        public IActionResult Excluir(int id)
        {
            try
            {
                bool apagado = _prefeituraRepository.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Cadastro apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato!";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, mais detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Cadastrar(PrefeituraModel prefeitura)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _prefeituraRepository.Cadastrar(prefeitura);
                    TempData["MensagemSucesso"] = "Cadastro realizado com sucesso";
                    return RedirectToAction("Index");
                }

                return View(prefeitura);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(PrefeituraModel prefeitura)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _prefeituraRepository.Editar(prefeitura);
                    TempData["MensagemSucesso"] = "Cadastro alterado com sucesso";
                    return RedirectToAction("Index");
                }
                return View(prefeitura);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }       
    }
}

Views/Prefeitura/ApagarConfirmacao.cshtml
@model PrefeituraModel

@{
    ViewData["title"] = "Excluir Prefeitura";
}

<h2 class="text-center my-4 display-3">Realmente deseja excluir (@Model.Municipio)?</h2>


<a role="button" class="btn btn-danger my-3 w-100" asp-controller="Prefeitura" asp-route-id="@Model.Id" asp-action="Excluir">Excluir</a>
<a role="button" class="btn btn-primary w-100" asp-controller="Prefeitura" asp-action="Index">Voltar</a>

Views/Prefeitura/Cadastrar.cshtml
@model PrefeituraModel

@{
    ViewData["title"] = "Cadastrar Prefeitura";
}

<h2 class="text-center my-4 display-3">Cadastro de Prefeitura</h2>


<form asp-controller="Prefeitura" asp-action="Cadastrar" method="post">
    <div class="form-group mt-2">
        <label for="Municipio">Município</label>
        <input type="text" class="form-control" asp-for="Municipio" placeholder="Digíte o Município">
        @Html.ValidationMessageFor(x => x.Municipio)
    </div>
    <div class="form-group mt-2">
        <label for="Nome">Nome</label>
        <input type="text" class="form-control" asp-for="NomeRH" placeholder="Digíte o Nome">
        @Html.ValidationMessageFor(x => x.NomeRH)
    </div>
    <div class="form-group mt-2">
        <label for="Email">E-mail</label>
        <input type="text" class="form-control" asp-for="EmailRH" placeholder="Digíte o E-mail">
        @Html.ValidationMessageFor(x => x.EmailRH)
    </div>
    <div class="form-group mt-2">
        <label for="Telefone">Telefone</label>
        <input type="text" class="form-control" asp-for="TelefoneRH" placeholder="Digíte o Telefone">
        @Html.ValidationMessageFor(x => x.TelefoneRH)
    </div>
    <button type="submit" class="btn btn-success mt-2 w-100">Cadastrar</button>
    <a role="button" class="btn btn-primary mt-2 w-100" asp-controller="Prefeitura" asp-action="Index">Voltar</a>
</form>

Views/Prefeitura/Editar.cshtml
@model PrefeituraModel

@{
    ViewData["title"] = "Editar Prefeitura";
}

<h2 class="text-center my-4 display-3">Edição de Prefeitura</h2>


<form asp-controller="Prefeitura" asp-action="Editar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="form-group mt-2">
        <label for="Municipio">Município</label>
        <input type="text" class="form-control" asp-for="Municipio" placeholder="Digíte o Município">
        @Html.ValidationMessageFor(x => x.Municipio)
    </div>
    <div class="form-group mt-2">
        <label for="Nome">Nome</label>
        <input type="text" class="form-control" asp-for="NomeRH" placeholder="Digíte o Nome">
        @Html.ValidationMessageFor(x => x.NomeRH)
    </div>
    <div class="form-group mt-2">
        <label for="Email">E-mail</label>
        <input type="text" class="form-control" asp-for="EmailRH" placeholder="Digíte o E-mail"> 
        @Html.ValidationMessageFor(x => x.EmailRH)
    </div>
    <div class="form-group mt-2">
        <label for="Telefone">Telefone</label>
        <input type="text" class="form-control" asp-for="TelefoneRH" placeholder="Digíte o Telefone">
        @Html.ValidationMessageFor(x => x.TelefoneRH)
    </div>
    <button type="submit" class="btn btn-success mt-2 w-100">Alterar</button>
    <a role="button" class="btn btn-primary mt-2 w-100" asp-controller="Prefeitura" asp-action="Index">Voltar</a>
</form>

Views/Prefeitura/Index.cshtml
@model IEnumerable<PrefeituraModel>

@{
    ViewData["title"] = "Lista de Prefeituras";
}

<h2 class="text-center my-4 display-3">Lista de Prefeituras</h2>

<br />

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success text-center" role="alert">
     <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
     @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger text-center" role="alert">
    <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
    @TempData["MensagemErro"]
</div>
}

<br />

<a class="btn btn-primary my-3" asp-controller="Prefeitura" asp-action="Cadastrar" role="button">Cadastro de Prefeitura</a>

<div class="table-responsive" id="br1">
    <table class="table table-hover" id="table-contatos">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Município</th>
            <th scope="col">Nome</th>
            <th scope="col">E-mail</th>
            <th scope="col">Telefone</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @if (Model != null && Model.Any())
        {
            @foreach (PrefeituraModel item in Model)
            {
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.Municipio</td>
                    <td>@item.NomeRH</td>
                    <td>@item.EmailRH</td>
                    <td>@item.TelefoneRH</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a role="button" class="btn btn-primary" asp-route-id="@item.Id" asp-controller="Prefeitura" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-route-id="@item.Id" asp-controller="Prefeitura" asp-action="ApagarConfirmacao">Excluir</a>
                        </div>
                    </td>
                </tr>
            }
        }

    </tbody>
</table>
</div>